services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "on-failure"
    container_name: markdown-note
    working_dir: /app
    command: go run ./app/main.go
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - CGO_ENABLED=1
    ports:
      - "3000:3000"
